### ISSUE TITLE
avoid callback hell

### ISSUE THREAD

**Issue by tmanolat** [thanashskyr/corporate_management_assistant#10]
https://github.com/thanashskyr/corporate_management_assistant/blob/e93be7490585e8cc0944238695adfb005fe77c21/backend/auth.js#L13

https://github.com/thanashskyr/corporate_management_assistant/blob/e93be7490585e8cc0944238695adfb005fe77c21/backend/login.js#L18

παιξε με async await καλύτερα παντου

**Comment by thanashskyr** [comment]
issue #10 fixed avoid callback hell
      - Removed callback function from auth.authenticateUser function and use of async-await
      - Removed callback function from jwt.storeToken function and use of async-await   
      - Use of async-await at login.js
